obstacle_range:  10.0 # 3.5
raytrace_range: 10.0 # 3.0

footprint: [[0.3425, 0.285], [-0.3425, 0.285], [-0.3425, -0.285], [0.3425, -0.285]] #570x685
#robot_radius: ir_of_robot
# inflation_radius: 0.1
track_unknown_space: false
resolution: 0.05

static_layer:
    enabled:              true
    map_topic:            "/map"


inflation_layer:
    enabled:              true
    cost_scaling_factor:  5  
    inflation_radius:     0.2

obstacle_layer:
    observation_sources: laser_scan_sensor
    footprint_clearing_enabled: true
    laser_scan_sensor: {data_type: LaserScan, sensor_frame: laser, clearing: true, marking: true, topic: /scan}

# observation_sources: laser_scan_sensor #, point_cloud_sensor

# laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}