global_costmap:
    global_frame: map
    robot_base_frame: base_link

    update_frequency: 5.0
    publish_frequency: 1.0
    transform_tolerance: 0.5
    # static_map: true
    rolling_windows: true

    plugins:
        - {name: static_layer,        type: "costmap_2d::StaticLayer"}
        # - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

    # static_layer:
    #     enabled:              true
    #     cost_scaling_factor:  10
    #     map_topic:            "/map"


    # inflation_layer:
    #     enabled:              true
    #     cost_scaling_factor:  5  
    #     inflation_radius:     0.1